version: 2.1

executors:
  machine-docker:
    machine:
      image: ubuntu-2204:current # enables full VM with Docker dind support
    working_directory: ~/project

jobs:
  build-and-test:
    executor: machine-docker
    steps:
      - checkout

      # ---------- Cache restore ----------
      - restore_cache:
          keys:
            - v1-ethash-docker-{{ checksum "Makefile" }}
            - v1-ethash-docker-

      # Restore previously cached docker images (if any)
      - run:
          name: Load cached Docker images
          command: |
            mkdir -p ~/.docker
            if [ -d ~/.docker ] && [ "$(ls -A ~/.docker)" ]; then
              for img in $(ls ~/.docker); do
                docker load -i ~/.docker/$img || true
              done
            fi

      # ---------- Install Hive & warm-up ----------
      - run:
          name: Install hive testing framework
          command: |
            go install github.com/karalabe/hive@latest

      - run:
          name: Prepare ethash DAG cache & run dry-run hive
          command: |
            export GOPATH=$(go env GOPATH)
            HIVE_DIR=$(dirname $(go list -f '{{ .Dir }}' -m github.com/karalabe/hive@latest))
            mkdir -p ${HIVE_DIR}/workspace/ethash ~/.ethash
            cp -r ~/.ethash/. ${HIVE_DIR}/workspace/ethash/ 2>/dev/null || true
            (cd ${HIVE_DIR} && hive --docker-noshell --client=NONE --test=. --sim=. --loglevel=6)

      # ---------- Build Geth ----------
      - run:
          name: Build geth binary
          command: make geth

      # ---------- Run hive tests with local geth ----------
      - run:
          name: Run hive with local geth
          command: |
            export GOPATH=$(go env GOPATH)
            HIVE_DIR=$(dirname $(go list -f '{{ .Dir }}' -m github.com/karalabe/hive@latest))
            cp ./build/bin/geth $HOME/geth
            (cd ${HIVE_DIR} && hive --docker-noshell --client=go-ethereum:local --override=$HOME/geth --test=. --sim=.)

      # ---------- Collect logs as artifacts ----------
      - run:
          name: Collect hive logs
          command: |
            mkdir -p /tmp/hive-logs
            export GOPATH=$(go env GOPATH)
            HIVE_DIR=$(dirname $(go list -f '{{ .Dir }}' -m github.com/karalabe/hive@latest))
            cp -r ${HIVE_DIR}/workspace/logs/. /tmp/hive-logs/ || true
      - store_artifacts:
          path: /tmp/hive-logs

      # ---------- Update caches ----------
      - run:
          name: Save Docker images into cache directory
          command: |
            mkdir -p ~/.docker
            for img in $(docker images --format '{{ .Repository }}'); do
              docker save "$img" > ~/.docker/$(echo "$img" | tr '/' ':').tar || true
            done
      - run:
          name: Save updated ethash DAGs
          command: |
            export GOPATH=$(go env GOPATH)
            HIVE_DIR=$(dirname $(go list -f '{{ .Dir }}' -m github.com/karalabe/hive@latest))
            mkdir -p ~/.ethash
            cp -r ${HIVE_DIR}/workspace/ethash/. ~/.ethash/ || true
      - save_cache:
          key: v1-ethash-docker-{{ checksum "Makefile" }}
          paths:
            - ~/.docker
            - ~/.ethash

workflows:
  version: 2
  hive-tests:
    jobs:
      - build-and-test 